import type { TaxProfile } from "./profiles";
/** Narrow identity words; ambiguous matches remain candidates for review, never a guessed universal rate. */
export const classificationRules: [TaxProfile, RegExp][] = [
  ["whisky", /ウイスキー|ウィスキー|whisk[ey]+|위스키/i],
  ["wine", /ワイン|赤ワイン|白ワイン|\bwine\b|와인/i],
  ["sake", /日本酒|清酒|純米|大吟醸|\bsake\b|사케|청주/i],
  ["brandy", /ブランデー|\bbrandy\b|브랜디|코냑|コニャック|cognac/i],
  ["cushion", /クッション|枕|쿠션|베개|\bcushion\b|\bpillow\b/i],
  ["toy", /ぬいぐるみ|玩具|봉제인형|장난감|\bplush\b|\btoy\b/i],
  ["apparel", /シャツ|衣類|티셔츠|의류|\bt-shirt\b/i],
  ["hosiery", /レギンス|レギング|靴下|양말|레깅스|\bleggings\b|\bsocks\b/i],
  ["recorded_media", /blu-ray|ブルーレイ|\bDVD\b|\bCD\b|음반/i],
  ["shoes", /スニーカー|靴(?!下)|운동화|신발|\bsneakers?\b|\bshoes?\b/i],
  ["umbrella", /傘|우산|\bumbrella\b/i],
  ["suitcase", /スーツケース|캐리어|여행가방|\bsuitcase\b/i],
  ["wallet", /財布|지갑|\bwallet\b/i],
  ["phone_case", /スマホケース|휴대폰\s*케이스|phone case/i],
  ["tent", /テント|텐트|\btent\b/i],
  ["towel", /タオル|수건|\btowel\b/i],
  ["bedsheet", /ベッドシーツ|침대\s*시트|bed ?sheet/i],
  ["curtain", /カーテン|커튼|\bcurtains?\b/i],
  ["shampoo", /シャンプー|샴푸|\bshampoo\b/i],
  ["lipstick", /口紅|립스틱|\blipstick\b/i],
  ["hand_cream", /ハンドクリーム|핸드크림|hand cream/i],
  ["stroller", /ベビーカー|유모차|\bstroller\b/i],
  ["diaper", /紙おむつ|기저귀|\bdiapers?\b/i],
  ["laptop", /ノートパソコン|ノートPC|노트북|\blaptop\b/i],
  ["computer", /デスクトップ|데스크톱|\bdesktop\b/i],
  ["keyboard", /キーボード|키보드|\bkeyboard\b/i],
  ["mouse", /マウス|마우스|computer mouse/i],
  ["smartphone", /スマートフォン|스마트폰|\bsmartphone\b/i],
  ["power_bank", /モバイルバッテリー|보조배터리|power bank/i],
  ["digital_camera", /デジタルカメラ|디지털카메라|digital camera/i],
  ["vacuum", /掃除機|청소기|vacuum cleaner/i],
  [
    "headphones",
    /ヘッドホン|イヤホン|헤드폰|이어폰|\bheadphones?\b|\bearbuds?\b/i,
  ],
  ["catalog_248", /書籍|雑誌|도서|서적|잡지|\bbooks?\b|\bmagazines?\b/i],
  ["catalog_31", /香水|향수|\bperfume\b/i],
  ["catalog_23", /健康食品|건강기능식품|dietary supplement/i],
];
